import type { CSSProperties } from 'react'

// Shared look for the bill edit and history screens — the app's purple, DM Sans.
const font = "'DM Sans', sans-serif"

export const S: Record<string, CSSProperties> = {
  overlay: { position: 'fixed', inset: 0, background: 'rgba(15,10,30,.45)', display: 'flex',
             alignItems: 'flex-start', justifyContent: 'center', padding: '32px 16px', zIndex: 1000, overflowY: 'auto' },
  card: { background: '#fff', borderRadius: 16, width: '100%', maxWidth: 900, boxShadow: '0 24px 64px rgba(0,0,0,.25)',
          fontFamily: font, color: '#1a0a2e', display: 'flex', flexDirection: 'column' },
  head: { display: 'flex', justifyContent: 'space-between', gap: 16, padding: '18px 22px', borderBottom: '1px solid #f3e8ff' },
  title: { fontSize: 18, fontWeight: 700 },
  sub: { fontSize: 12.5, color: '#64748b', marginTop: 3, maxWidth: 620 },
  x: { background: 'none', border: 'none', cursor: 'pointer', color: '#64748b', padding: 4, height: 30 },
  body: { padding: '16px 22px', display: 'flex', flexDirection: 'column', gap: 12 },
  foot: { display: 'flex', justifyContent: 'flex-end', gap: 10, padding: '14px 22px', borderTop: '1px solid #f3e8ff' },
  loading: { padding: 40, display: 'flex', gap: 10, alignItems: 'center', justifyContent: 'center', color: '#64748b' },
  section: { fontSize: 12, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.05em', color: '#7c3aed', margin: '4px 0 6px' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: { textAlign: 'left', fontSize: 11.5, fontWeight: 700, color: '#64748b', padding: '6px 6px', borderBottom: '1px solid #e9d5ff' },
  td: { padding: '7px 6px', borderBottom: '1px solid #f5f3ff', verticalAlign: 'top' },
  input: { padding: '8px 10px', border: '1px solid #e2e8f0', borderRadius: 8, fontSize: 13, fontFamily: font, boxSizing: 'border-box' },
  num: { width: '100%', padding: '6px 8px', border: '1px solid #e2e8f0', borderRadius: 8, fontSize: 13, fontFamily: font, boxSizing: 'border-box' },
  row: { display: 'flex', gap: 8, alignItems: 'center' },
  grid2: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 18 },
  muted: { fontSize: 12, color: '#64748b', marginTop: 4 },
  changed: { color: '#b45309', fontWeight: 600, fontSize: 12 },
  note: { background: '#f5f3ff', border: '1px solid #e9d5ff', color: '#6b21a8', borderRadius: 10, padding: '8px 12px', fontSize: 12.5 },
  error: { background: '#fef2f2', border: '1px solid #fecaca', color: '#b91c1c', borderRadius: 10, padding: '8px 12px', fontSize: 12.5 },
  authBox: { marginTop: 8, padding: 10, borderRadius: 10, background: '#fffbeb', border: '1px solid #fde68a' },
  totals: { display: 'flex', flexWrap: 'wrap', gap: '8px 18px', alignItems: 'baseline', padding: '10px 14px',
            background: '#faf5ff', borderRadius: 10, fontSize: 13 },
  results: { border: '1px solid #e9d5ff', borderRadius: 10, overflow: 'hidden' },
  result: { display: 'flex', gap: 8, alignItems: 'center', width: '100%', padding: '8px 12px', background: '#fff', border: 'none',
            borderBottom: '1px solid #f5f3ff', cursor: 'pointer', fontSize: 13, fontFamily: font, textAlign: 'left' },
  btnPrimary: { padding: '10px 20px', background: '#9333ea', color: '#fff', border: 'none', borderRadius: 10, fontSize: 14,
                fontWeight: 600, cursor: 'pointer', fontFamily: font },
  btnOutline: { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '8px 14px', background: '#fff', color: '#9333ea',
                border: '1px solid #e9d5ff', borderRadius: 10, fontSize: 13, cursor: 'pointer', fontFamily: font, whiteSpace: 'nowrap' },
  btnTiny: { padding: '6px 10px', background: '#f5f3ff', color: '#7c3aed', border: '1px solid #e9d5ff', borderRadius: 8,
             fontSize: 12, cursor: 'pointer', fontFamily: font },
  iconBtn: { background: 'none', border: 'none', color: '#dc2626', cursor: 'pointer', padding: 4 },
  link: { background: 'none', border: 'none', color: '#9333ea', cursor: 'pointer', padding: 0, fontSize: 12, textDecoration: 'underline' },
  badge: { display: 'inline-block', marginTop: 4, padding: '2px 8px', borderRadius: 20, background: '#fef3c7', color: '#92400e',
           fontSize: 11, fontWeight: 700, border: 'none', cursor: 'pointer', fontFamily: font },
}
